#' The application User-Interface
#' 
#' @param request Internal parameter for `{shiny}`. 
#'     DO NOT REMOVE.
#' @import shiny
#' @import magrittr
#' @noRd
app_ui <- function(request) {
  tagList(
    # Leave this function for adding external resources
    golem_add_external_resources(),
    # List the first level UI elements here 
    navbarPage("Bioscreen growth curves analysis",
               theme = shinythemes::shinytheme("united"),
               tabPanel("Load data",
                        
                        
                        sidebarLayout(
                          sidebarPanel(
                            radioButtons('czy_filtr', 'Load previously filtered data?', 
                                         choices = c('Yes', 'No'), inline = TRUE, selected = 'No'),
                            conditionalPanel(condition = 'input.czy_filtr == "No"',
                                             "Load plate map and bioscreen data", 
                                             fileInput('dane_mapa', 'Choose excel file with plate map'),
                                             radioButtons('format', "Choose bioscreen data type: excel file or csv/txt (generated by the bioscreen)?", 
                                                          choices = c('xlsx', 'csv', 'txt'), inline = TRUE, selected = 'csv'),
                                             fileInput('dane_bio', 'Choose file with bioscreen data'),
                                             numericInput('linie_usun', "How many lines should be skipped in excel file (usually 2)", 2),
                                             numericInput('czas_bio', 'Time lapse in measurement?', 10),
                                             numericInput("usun_blank", "Remove blank values if the difference between maximum and minimu exceeds value:",
                                                          value = 0.1, min = 0, max = 1, step = 0.05),
                                             checkboxInput('pomin_blank', "Subtract blank values from data?", value = TRUE)
                            ),
                            conditionalPanel(condition = 'input.czy_filtr == "Yes"',
                                             fileInput('dane_filtr', 'Choose csv file containing data filtered by the bioscreen app')
                            ),
                            width = 3
                            
                          ),
                          
                          
                          mainPanel(
                            h4("Data in a tidy long format"),
                            tableOutput("dane"),
                            h4("Plate map"),
                            tableOutput("mapa"),
                            conditionalPanel(condition =  'input.pomin_blank==true', 
                                             h4("Blank absorbance - medium"),
                                             plotOutput("wykres_blank")
                            ),
                            width = 9
                          )
                        )
               ),
               tabPanel("Filtering",
                        
                        
                        sidebarLayout(
                          sidebarPanel(
                            numericInput('filtr_up', 'Remove curves which exceed absorbance threshold', 1.25, step = 0.1),
                            numericInput('filtr_down', 'Remove curves which are below absorbance threshold', 0.01, step = 0.01),
                            numericInput('filtr_mediana', 'Remove outlier curves - exceed mean distance to absorbance median', 0.08, step = 0.01),
                            radioButtons('wyrownac', 'Should curves start at zero?', 
                                         choices = c('Yes', 'No'), inline = TRUE, selected = 'Yes'),
                            downloadButton("downloadData", "Download filtered data"),
                            width = 3
                            
                            
                          ),
                          
                          
                          mainPanel(
                            plotOutput("krzywe", height = "700px"),
                            width = 9
                          )
                        )
               ),
               tabPanel("Growth curves",
                        
                        
                        sidebarLayout(
                          sidebarPanel(
                            uiOutput("filtr_czas"),
                            uiOutput("szczepy"),
                            uiOutput("warunki"),
                            radioButtons('smooth', 'Show trend line (loess)?',
                                         choices = c('Yes', 'No'), inline = TRUE, selected = 'No'),
                            numericInput('span', 'Loess smooothing degree',
                                         value = 0.75, step = 0.05),
                            radioButtons('sd', 'Show standard deviation?', 
                                         choices = c('Yes', 'No'), inline = TRUE, selected = 'No'),
                            radioButtons('ll', 'Show log-logistic model? (currently works only if a single condition is chosen)', 
                                         choices = c('Yes', 'No'), inline = TRUE, selected = 'No'),
                            radioButtons('hide_curves', 'Hide growth curves?',
                                         choices = c('Yes', 'No'), inline = TRUE, selected = 'No'),
                            radioButtons('plot_type', 'Choose plot type for download?', choices = list('png', 'svg'), 
                                         inline = TRUE),
                            downloadButton('download_wykres', 'Download plot'),
                            numericInput('width', 'Plot width [cm]', 20, min = 5, max = 35),
                            numericInput('height', 'Plot height [cm]', 14, min = 5, max = 35),
                            numericInput('res', 'Resolution', 200, min = 100, max = 500),
                            textInput('xlab', 'X axis name', value = 'Time [h]'),
                            textInput('ylab', 'Y axis name', value = 'OD'),
                            textInput('legend', 'Legend title', value = 'Strain'),
                            width = 3
                          ),
                          
                          
                          mainPanel(
                            plotOutput("krzywe_final", height = "700px", width = '100%'),
                            width = 9
                          )
                        )
               ),
               tabPanel('Help',
                        p(strong('1. Load data -'),' - required files:'),
                        p('* .csv file generated by the bioscreen or saved in xlsx format'),
                        p('* xlsx file with the plate map - allows correct linking of growth curves with strain names and conditions'),
                        p('Each strain name should be in format: strain/condition. If all strains were grown in the same conditions then they can be saved as /0.'),
                        p('If well contains only medium and is supposed to be substracted from other growth curves it should be saved as blank,
there can be more than one blank on the plate, their value will be averaged before substracting. There is an option to analyze growth curves without any blanks present.'),
                        p('Example plate map and data file are available on the Github page.'),
                        p(strong('2. Filtering -'),' allows removal if growth curves with too high absorbance, too low absorbance 
                        or too different from other replicates'),
                        p('Filtered data can be saved in csv format for further analysis'),
                        p(strong('3. Gowth curves'),' - Plots averaged growth curves for all filtered strains. 
                        Only certain strains or growth conditions can be chosen,
                        standard deviation, loess trend line or log-logistic model (currently only when single conditions are chosen) can be added to the plot'),
                        p('Finished plot can be saved in png or svg format')
                        
               )
    )
  )
  
}

#' Add external Resources to the Application
#' 
#' This function is internally used to add external 
#' resources inside the Shiny application. 
#' 
#' @import shiny
#' @importFrom golem add_resource_path activate_js favicon bundle_resources
#' @noRd
golem_add_external_resources <- function(){
  
  add_resource_path(
    'www', app_sys('app/www')
  )
  
  tags$head(
    favicon(),
    bundle_resources(
      path = app_sys('app/www'),
      app_title = 'bioscreen'
    )
    # Add here other external resources
    # for example, you can add shinyalert::useShinyalert() 
  )
}

